name: deploy to lambda
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy lambda function
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: AWS Lambda Deploy
        if: github.ref == 'refs/heads/main'
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: getResume
          source: aws/get-resume.js
